apiVersion: v1
kind: Pod
metadata:
  name: boltwolf-networks-headless-pod
  namespace: neosvr
spec:
  hostNetwork: true
  containers:
    - name: neosvr-headless
      image: registry.gitlab.com/boltwolf/neosvr-headless:latest
      tty: true
      stdin: true
      env:
        - name: STEAMBETA
          valueFrom:
            secretKeyRef:
              name: steambeta
              key: STEAMBETA
              optional: false
        - name: STEAMBETAPASSWORD
          valueFrom:
            secretKeyRef:
              name: steambetapassword
              key: STEAMBETAPASSWORD
              optional: false
        - name: STEAMLOGIN
          valueFrom:
            secretKeyRef:
              name: steamlogin
              key: STEAMLOGIN
              optional: false
      volumeMounts:
        - name: config-vol
          mountPath: /Config
          readOnly: true
        - name: logs-vol
          mountPath: /Logs
  volumes:
    - name: config-vol
      configMap:
        name: boltwolf-networks-headless-config
        items:
          - key: Config.json
            path: Config.json
    - name: logs-vol
      emptyDir: {}
